#!/usr/bin/env python3

from __future__ import annotations

import argparse
from pathlib import Path
from typing import Any

import yaml


ROOT = Path(__file__).resolve().parents[2]
ACTIVE_CYCLE_PATH = ROOT / "planning" / "cycles" / "active.yaml"


def save_yaml(path: Path, payload: dict[str, Any]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", encoding="utf-8") as handle:
        yaml.safe_dump(payload, handle, sort_keys=False, allow_unicode=False)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Create or replace the active cycle manifest")
    parser.add_argument("--id", required=True, help="Cycle id, eg 2027-02-15_new_goal")
    parser.add_argument("--start-date", required=True, help="Cycle start date YYYY-MM-DD")
    parser.add_argument("--end-date", required=True, help="Cycle end date YYYY-MM-DD")
    parser.add_argument("--goal-race-slug", required=True, help="Goal race slug or identifier")
    parser.add_argument("--master-plan-path", default="planning/master_plan.md")
    parser.add_argument("--blocks-path", default="planning/blocks")
    parser.add_argument("--weeks-path", default="planning/weeks")
    parser.add_argument("--goal-gates-path", default="planning/goal_gates.yaml")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = {
        "cycle": {
            "id": args.id,
            "status": "active",
            "start_date": args.start_date,
            "end_date": args.end_date,
            "goal_race_slug": args.goal_race_slug,
            "master_plan_path": args.master_plan_path,
            "blocks_path": args.blocks_path,
            "weeks_path": args.weeks_path,
            "goal_gates_path": args.goal_gates_path,
            "notes": "Generated by start_cycle.py",
        }
    }
    save_yaml(ACTIVE_CYCLE_PATH, payload)
    print(f"Active cycle manifest written to {ACTIVE_CYCLE_PATH.relative_to(ROOT)}")


if __name__ == "__main__":
    main()
